AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Cloudformation CD/CI with Github Actions : Lambda6

Parameters:
  LambdaFunctionRole:
    Description: ARN Lambda function role
    Type: String

Resources:
  Lambda6Function:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: Lambda6-Cloudformation
      Description: Sample .Net Core Lambda function deployed by Cloudformation & Github Actions
      Handler: Lambda6::Lambda6.Function::FunctionHandler
      Runtime: dotnet6
      Role: !Sub ${LambdaFunctionRole}
      Code:
        S3Bucket: artifact-bucket-gh128
        S3Key: lambda6/code.zip

Outputs:
  LambdaARN:
    Description: Arn Lambda6 function
    Value: !GetAtt Lambda6Function.Arn
