# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Core Build + CloudFormation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore ./test/Lambda6.Tests/Lambda6.Tests.csproj --runtime linux-x64

      - name: Build project
        run: dotnet build ./test/Lambda6.Tests/Lambda6.Tests.csproj --no-restore

      - name: Testing
        run: dotnet test test/Lambda6.Tests/Lambda6.Tests.csproj --no-build --verbosity normal

      - name: Publish
        run: dotnet publish ./src/Lambda6/Lambda6.csproj -r linux-x64 -c Release -o ./artifact/publish --no-self-contained --no-restore

      - name: Zipping Published File
        uses: thedoctor0/zip-release@main
        with:
          type: "zip"
          directory: ./artifact/publish
          filename: ../code.zip

      - name: Copy CloudFormation Template to Artifact
        run: cp ./.cloudformation/template.yaml ./artifact/template.yaml

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Lambda6-artifact
          path: |
            ./artifact
            !./artifact/publish

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ASSUME }}
          aws-region: ap-southeast-1

      - name: Upload the code to S3
        run: aws s3 sync ./artifact s3://artifact-bucket-gh128/lambda6 --exclude "*" --include "*.zip"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: Lambda6-artifact
          path: artifact

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ASSUME }}
          aws-region: ap-southeast-1

      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: Lambda6-ghaction-stack
          template: artifact/template.yaml
          parameter-overrides: >-
            LambdaFunctionRole=${{ secrets.LAMBDA_FUNCTION_ROLE }}
          no-fail-on-empty-changeset: "1"
          capabilities: CAPABILITY_AUTO_EXPAND
