# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Core Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: |
          dotnet restore src/Lambda6/Lambda6.csproj
          dotnet restore test/Lambda6.Tests/Lambda6.Tests.csproj
      - name: Build
        run: dotnet build test/Lambda6.Tests/Lambda6.Tests.csproj --no-restore
      - name: Test
        run: dotnet test test/Lambda6.Tests/Lambda6.Tests.csproj --no-build --verbosity normal
